const GAME_STATE_FAILED = 'GAME_STATE_FAILED';
const GAME_STATE_WON = 'GAME_STATE_WON';
const MAX_ATTEMPTS = 6;
const GAME_STATE_KEYS = ['gameID', 'category', 'failsCounter', 'encodedPhrase', 'endState'];
const LETTER_STATUS_CORRECT = 'LETTER_STATUS_CORRECT';
const LETTER_STATUS_INCORRECT = 'LETTER_STATUS_INCORRECT';
const KEYBOARD_KEY = 'KEYBOARD_KEY';
const KeyboardType = {
    QWERTY: 'QWERTY',
    ALPHABETICAL: 'ALPHABETICAL',
};

module.exports = {
    GAME_STATE_FAILED,
    GAME_STATE_WON,
    MAX_ATTEMPTS,
    GAME_STATE_KEYS,
    LETTER_STATUS_CORRECT,
    LETTER_STATUS_INCORRECT,
    KEYBOARD_KEY,
    KeyboardType,
};
